// The expectations come ONLY from testdata/conversation/v1/render/turn-rows.json (generated by purdex-ios, U3 plan D9 gate).
// The inputs are the MANIFEST cases' `expected.json` (turns) and `children/<agent>.expected.json` (a pseudo-turn each).
// Nothing here computes an expected value; the few tests below the parity block feed hand-made steps for rules the
// golden cases do not reach (a running run, an hour-long span) and say so.
import { describe, expect, it } from 'vitest'
import type { ConversationItem, StepItem } from './types'
import { formatSpan, makeRun, segmentItems, turnRows } from './turn-row'
import golden from '../../../../testdata/conversation/v1/render/turn-rows.json'
import manifest from '../../../../testdata/conversation/v1/MANIFEST.json'

type Item = ConversationItem
const fixtures = import.meta.glob('../../../../testdata/conversation/v1/cc-transcript/*/expected.json', { eager: true, import: 'default' }) as Record<string, { conversation: { turns: Array<{ id: string; index: number; items: Item[] }> } }>
const childFixtures = import.meta.glob('../../../../testdata/conversation/v1/cc-transcript/*/children/*.expected.json', { eager: true, import: 'default' }) as Record<string, { items: Item[] }>

const fixtureOf = (name: string) => fixtures[`../../../../testdata/conversation/v1/cc-transcript/${name}/expected.json`]
const childOf = (name: string, agent: string) => childFixtures[`../../../../testdata/conversation/v1/cc-transcript/${name}/children/${agent}.expected.json`]

interface GoldenTurn { turn_id: string; index: number; runs: Array<{ step_ids: string[]; running: boolean; text: string | null; latest?: string }> }
const cases = golden.cases as unknown as Array<{ name: string; turns: GoldenTurn[]; children?: Array<{ agent_id: string; turns: GoldenTurn[] }> }>

const withSteps = (items: Item[]) => items.map((it, index) => ({ ...it, index }) as Item)
const rowsOf = (turns: Array<{ id: string; index: number; items: Item[] }>) =>
  turns.map((t) => turnRows({ ...t, items: withSteps(t.items) })).filter((r) => r.runs.length > 0)
const view = (rows: ReturnType<typeof rowsOf>): GoldenTurn[] =>
  rows.map((r) => ({ turn_id: r.turnId, index: r.index, runs: r.runs.map((x) => ({ step_ids: x.stepIds, running: x.running, text: x.text })) }))

describe('turn rows parity with the iOS golden file', () => {
  it('covers every MANIFEST case, in order', () => {
    expect(cases.map((c) => c.name)).toEqual(manifest.cases.map((c) => c.name))
    expect(cases).toHaveLength(21)
  })

  for (const c of cases) {
    it(`case ${c.name}: runs, step ids and text equal`, () => {
      const fx = fixtureOf(c.name)
      expect(fx, 'fixture loaded').toBeDefined()
      expect(view(rowsOf(fx.conversation.turns))).toEqual(c.turns.map((t) => ({ turn_id: t.turn_id, index: t.index, runs: t.runs.map((r) => ({ step_ids: r.step_ids, running: r.running, text: r.text })) })))
      for (const ch of c.children ?? []) {
        const child = childOf(c.name, ch.agent_id)
        expect(child, 'child fixture loaded').toBeDefined()
        // A subagent file is one pseudo-turn whose id is its first item's id.
        const got = rowsOf([{ id: child.items[0].id, index: 0, items: child.items }])
        expect(view(got)).toEqual(ch.turns.map((t) => ({ turn_id: t.turn_id, index: t.index, runs: t.runs.map((r) => ({ step_ids: r.step_ids, running: r.running, text: r.text })) })))
      }
    })
  }

  it('every step of every turn lands in exactly one run', () => {
    for (const c of cases) {
      for (const t of fixtureOf(c.name).conversation.turns) {
        const ids = t.items.filter((i) => i.type === 'step').map((i) => i.id)
        const inRuns = turnRows({ ...t, items: withSteps(t.items) }).runs.flatMap((r) => r.stepIds)
        expect(inRuns).toEqual(ids)
      }
    }
  })
})

// Hand-made inputs for rules the golden file has no case for (README: "the current golden cases have no running run").
const step = (id: string, over: Partial<StepItem> = {}): StepItem =>
  ({ type: 'step', id, at: 1, index: 0, kind: 'execute', tool: 'Bash', status: 'done', summary: id, started_at: 1000, duration_ms: 1000, input: {}, ...over })

describe('rules without a golden case', () => {
  it('a run with a running step is the live progress: no text, latest = category + summary of its last step, clock from the first start', () => {
    const run = makeRun([step('a', { started_at: 5000 }), step('b', { kind: 'edit', status: 'running', summary: 'src/x.ts', started_at: 9000 })])
    expect(run.running).toBe(true)
    expect(run.text).toBeNull()
    expect(run.latest).toBe('編輯 src/x.ts')
    expect(run.startedAt).toBe(5000)
  })

  it('a finished run has no latest', () => {
    expect(makeRun([step('a')]).latest).toBeUndefined()
  })

  it('thinking between steps does not break a run; text, agent_text and system do; trailing thinking is not a run', () => {
    const th = (id: string) => ({ type: 'thinking', id, at: 1, index: 0 }) as Item
    const at = { type: 'agent_text', id: 'm', at: 1, index: 0, markdown: 'x' } as Item
    const segs = segmentItems([step('a'), th('t1'), step('b'), at, step('c'), th('t2')])
    expect(segs.map((s) => (s.kind === 'run' ? s.run.stepIds.join('+') : s.item.id))).toEqual(['a+b', 'm', 'c', 't2'])
  })

  it('formats the span as 秒 / 分 / 分 秒 / 時 / 時 分', () => {
    expect([0, 4400, 60_000, 95_000, 3_600_000, 5_400_000].map(formatSpan)).toEqual(['0 秒', '4 秒', '1 分', '1 分 35 秒', '1 時', '1 時 30 分'])
  })

  it('counts follow the category order, failed / denied / interrupted are separate and only when above zero', () => {
    const run = makeRun([
      step('1', { kind: 'task' }), step('2', { kind: 'read', status: 'failed' }), step('3', { kind: 'weird' }),
      step('4', { kind: 'edit', status: 'denied', denial: 'user-rejected' }), step('5', { status: 'denied', denial: 'interrupted' }),
    ])
    expect(run.text).toBe('處理了 1 秒 · 1 個指令、1 個編輯、1 個讀取、1 個子 agent、1 個其他 · 1 失敗 · 1 已拒絕 · 1 已中斷')
  })
})
